[machine]
type = "desktop"
wm = "hyprland"
install_packages = false
install_optional = false

[packages.linux.arch]
official = [
  "base-devel",
  "bat",
  "btop",
  "curl",
  "direnv",
  "eza",
  "fd",
  "fzf",
  "git",
  "gnupg",
  "jq",
  "neovim",
  "pass",
  "ripgrep",
  "starship",
  "tmux",
  "zsh",
]
aur = []

[packages.darwin]
brew = [
  "bat",
  "btop",
  "direnv",
  "eza",
  "fd",
  "fzf",
  "git",
  "gnupg",
  "neovim",
  "pass",
  "ripgrep",
  "starship",
  "tmux",
  "zsh",
]
cask = []
