#!/bin/zsh

# K8s
alias k="kubectl"
alias kx='f() { [ "$1" ] && kubectl config use-context $1 || kubectl config current-context ; } ; f'
alias kn='f() { [ "$1" ] && kubectl config set-context --current --namespace $1 || kubectl config view --minify | grep namespace | cut -d" " -f6 ; } ; f'
alias klogin="tsh login --proxy=teleport.k8s-mgmt.stghouzz.com:443 --auth=github"
alias klogout="tsh logout"
alias kls="tsh kube ls"
alias ksw="tsh kube login"
alias kst="tsh status"
