[font]
size = 11.0
offset = { x = 0, y = -1 } # This moves lines 1px closer together
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
# family = "RecMonoLinear Nerd Font Propo"
style = "Regular"
# style = "Bold"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchStart"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchEnd"
key = "Q"
mode = "Vi|Search"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"

[window]
decorations = "none"
opacity = 0.8
# option_as_alt = "Both"
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 38

[window.padding]
x = 2
y = 2

[general]
import = [
  # "/home/ll931217/.config/alacritty/tokyo-night-storm.toml",
  "/home/ll931217/.config/alacritty/kanso.toml",
  # "/home/ll931217/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
]

[terminal]
osc52 = "CopyPaste"
