# Kansō Zen - An Elegant Evolution of Kanagawa
# Repository: https://github.com/webhooked/kanso.nvim

[colors.primary]
background = "#101010" # Deep Zen Dark
foreground = "#DCD7BA" # Fuji White

[colors.cursor]
text = "#101010"
cursor = "#DCD7BA"

[colors.selection]
text = "CellForeground"
background = "#2D4F67" # Wave Blue

[colors.normal]
black   = "#16161D" # Sumi Ink
red     = "#C34043" # Autumn Red
green   = "#76946A" # Autumn Green
yellow  = "#C0A36E" # Boat Yellow
blue    = "#7E9CD8" # Crystal Blue
magenta = "#957FB8" # Oni Violet
cyan    = "#6A9589" # Wave Aqua
white   = "#C8C093" # Old White

[colors.bright]
black   = "#727169" # Fuji Gray
red     = "#E82424" # Samurai Red
green   = "#98BB6C" # Spring Green
yellow  = "#E6C384" # Carp Yellow
blue    = "#7FB4CA" # Spring Blue
magenta = "#938AA9" # Spring Violet
cyan    = "#7AA89F" # Wave Aqua 2
white   = "#DCD7BA" # Fuji White
